export type Item = {
  id: string;
  name: string;
  category: 'Framework' | 'Library' | 'Tool' | 'Database' | 'Language' | 'Cloud' | 'Testing' | 'DevOps';
  price: number;
};

export const items: Item[] = [
  // Frontend Frameworks
  { id: '1', name: 'React', category: 'Framework', price: 0 },
  { id: '2', name: 'Vue.js', category: 'Framework', price: 0 },
  { id: '3', name: 'Angular', category: 'Framework', price: 0 },
  { id: '4', name: 'Next.js', category: 'Framework', price: 0 },
  { id: '5', name: 'Nuxt.js', category: 'Framework', price: 0 },
  { id: '6', name: 'Svelte', category: 'Framework', price: 0 },
  { id: '7', name: 'SvelteKit', category: 'Framework', price: 0 },
  { id: '8', name: 'Gatsby', category: 'Framework', price: 0 },
  { id: '9', name: 'Remix', category: 'Framework', price: 0 },
  { id: '10', name: 'Solid.js', category: 'Framework', price: 0 },
  { id: '11', name: 'Qwik', category: 'Framework', price: 0 },
  { id: '12', name: 'Alpine.js', category: 'Framework', price: 0 },
  { id: '13', name: 'Lit', category: 'Framework', price: 0 },
  { id: '14', name: 'Stencil', category: 'Framework', price: 0 },
  { id: '15', name: 'Ember.js', category: 'Framework', price: 0 },
  { id: '16', name: 'Backbone.js', category: 'Framework', price: 0 },
  { id: '17', name: 'Meteor', category: 'Framework', price: 0 },
  { id: '18', name: 'Preact', category: 'Framework', price: 0 },
  { id: '19', name: 'Mithril', category: 'Framework', price: 0 },
  { id: '20', name: 'Riot.js', category: 'Framework', price: 0 },
  
  // Backend Frameworks
  { id: '21', name: 'Express.js', category: 'Framework', price: 0 },
  { id: '22', name: 'Koa.js', category: 'Framework', price: 0 },
  { id: '23', name: 'Fastify', category: 'Framework', price: 0 },
  { id: '24', name: 'Hapi.js', category: 'Framework', price: 0 },
  { id: '25', name: 'NestJS', category: 'Framework', price: 0 },
  { id: '26', name: 'Django', category: 'Framework', price: 0 },
  { id: '27', name: 'Flask', category: 'Framework', price: 0 },
  { id: '28', name: 'FastAPI', category: 'Framework', price: 0 },
  { id: '29', name: 'Ruby on Rails', category: 'Framework', price: 0 },
  { id: '30', name: 'Laravel', category: 'Framework', price: 0 },
  { id: '31', name: 'Symfony', category: 'Framework', price: 0 },
  { id: '32', name: 'Spring Boot', category: 'Framework', price: 0 },
  { id: '33', name: 'Quarkus', category: 'Framework', price: 0 },
  { id: '34', name: 'Micronaut', category: 'Framework', price: 0 },
  { id: '35', name: 'ASP.NET Core', category: 'Framework', price: 0 },
  { id: '36', name: 'Phoenix', category: 'Framework', price: 0 },
  { id: '37', name: 'Gin', category: 'Framework', price: 0 },
  { id: '38', name: 'Echo', category: 'Framework', price: 0 },
  { id: '39', name: 'Fiber', category: 'Framework', price: 0 },
  { id: '40', name: 'Actix Web', category: 'Framework', price: 0 },

  // Libraries
  { id: '41', name: 'Redux Toolkit', category: 'Library', price: 0 },
  { id: '42', name: 'Zustand', category: 'Library', price: 0 },
  { id: '43', name: 'Jotai', category: 'Library', price: 0 },
  { id: '44', name: 'Valtio', category: 'Library', price: 0 },
  { id: '45', name: 'Recoil', category: 'Library', price: 0 },
  { id: '46', name: 'MobX', category: 'Library', price: 0 },
  { id: '47', name: 'TanStack Query', category: 'Library', price: 0 },
  { id: '48', name: 'SWR', category: 'Library', price: 0 },
  { id: '49', name: 'Apollo Client', category: 'Library', price: 0 },
  { id: '50', name: 'Relay', category: 'Library', price: 0 },
  { id: '51', name: 'React Router', category: 'Library', price: 0 },
  { id: '52', name: 'Reach Router', category: 'Library', price: 0 },
  { id: '53', name: 'Vue Router', category: 'Library', price: 0 },
  { id: '54', name: 'Vuex', category: 'Library', price: 0 },
  { id: '55', name: 'Pinia', category: 'Library', price: 0 },
  { id: '56', name: 'NgRx', category: 'Library', price: 0 },
  { id: '57', name: 'RxJS', category: 'Library', price: 0 },
  { id: '58', name: 'Lodash', category: 'Library', price: 0 },
  { id: '59', name: 'Ramda', category: 'Library', price: 0 },
  { id: '60', name: 'Underscore.js', category: 'Library', price: 0 },
  { id: '61', name: 'Moment.js', category: 'Library', price: 0 },
  { id: '62', name: 'Day.js', category: 'Library', price: 0 },
  { id: '63', name: 'date-fns', category: 'Library', price: 0 },
  { id: '64', name: 'Axios', category: 'Library', price: 0 },
  { id: '65', name: 'Fetch', category: 'Library', price: 0 },
  { id: '66', name: 'Socket.io', category: 'Library', price: 0 },
  { id: '67', name: 'Three.js', category: 'Library', price: 0 },
  { id: '68', name: 'D3.js', category: 'Library', price: 0 },
  { id: '69', name: 'Chart.js', category: 'Library', price: 0 },
  { id: '70', name: 'Recharts', category: 'Library', price: 0 },
  { id: '71', name: 'Victory', category: 'Library', price: 0 },
  { id: '72', name: 'Framer Motion', category: 'Library', price: 0 },
  { id: '73', name: 'React Spring', category: 'Library', price: 0 },
  { id: '74', name: 'Lottie', category: 'Library', price: 0 },
  { id: '75', name: 'GSAP', category: 'Library', price: 0 },
  { id: '76', name: 'Anime.js', category: 'Library', price: 0 },
  { id: '77', name: 'Styled Components', category: 'Library', price: 0 },
  { id: '78', name: 'Emotion', category: 'Library', price: 0 },
  { id: '79', name: 'Stitches', category: 'Library', price: 0 },
  { id: '80', name: 'Material-UI', category: 'Library', price: 0 },
  { id: '81', name: 'Ant Design', category: 'Library', price: 0 },
  { id: '82', name: 'Chakra UI', category: 'Library', price: 0 },
  { id: '83', name: 'Mantine', category: 'Library', price: 0 },
  { id: '84', name: 'React Bootstrap', category: 'Library', price: 0 },
  { id: '85', name: 'Semantic UI React', category: 'Library', price: 0 },
  { id: '86', name: 'Headless UI', category: 'Library', price: 0 },
  { id: '87', name: 'Radix UI', category: 'Library', price: 0 },
  { id: '88', name: 'React Aria', category: 'Library', price: 0 },
  { id: '89', name: 'Reach UI', category: 'Library', price: 0 },
  { id: '90', name: 'Blueprint.js', category: 'Library', price: 0 },

  // Development Tools
  { id: '91', name: 'Vite', category: 'Tool', price: 0 },
  { id: '92', name: 'Webpack', category: 'Tool', price: 0 },
  { id: '93', name: 'Parcel', category: 'Tool', price: 0 },
  { id: '94', name: 'Rollup', category: 'Tool', price: 0 },
  { id: '95', name: 'esbuild', category: 'Tool', price: 0 },
  { id: '96', name: 'Snowpack', category: 'Tool', price: 0 },
  { id: '97', name: 'Turbopack', category: 'Tool', price: 0 },
  { id: '98', name: 'Rome', category: 'Tool', price: 0 },
  { id: '99', name: 'Biome', category: 'Tool', price: 0 },
  { id: '100', name: 'SWC', category: 'Tool', price: 0 },
  { id: '101', name: 'Babel', category: 'Tool', price: 0 },
  { id: '102', name: 'TypeScript', category: 'Tool', price: 0 },
  { id: '103', name: 'ESLint', category: 'Tool', price: 0 },
  { id: '104', name: 'Prettier', category: 'Tool', price: 0 },
  { id: '105', name: 'Husky', category: 'Tool', price: 0 },
  { id: '106', name: 'lint-staged', category: 'Tool', price: 0 },
  { id: '107', name: 'Commitizen', category: 'Tool', price: 0 },
  { id: '108', name: 'Conventional Commits', category: 'Tool', price: 0 },
  { id: '109', name: 'Semantic Release', category: 'Tool', price: 0 },
  { id: '110', name: 'Changesets', category: 'Tool', price: 0 },
  { id: '111', name: 'Lerna', category: 'Tool', price: 0 },
  { id: '112', name: 'Rush', category: 'Tool', price: 0 },
  { id: '113', name: 'Nx', category: 'Tool', price: 0 },
  { id: '114', name: 'Turborepo', category: 'Tool', price: 0 },
  { id: '115', name: 'Yarn', category: 'Tool', price: 0 },
  { id: '116', name: 'npm', category: 'Tool', price: 0 },
  { id: '117', name: 'pnpm', category: 'Tool', price: 0 },
  { id: '118', name: 'Bun', category: 'Tool', price: 0 },
  { id: '119', name: 'Node.js', category: 'Tool', price: 0 },
  { id: '120', name: 'Deno', category: 'Tool', price: 0 },

  // CSS Tools
  { id: '121', name: 'Tailwind CSS', category: 'Tool', price: 0 },
  { id: '122', name: 'Bootstrap', category: 'Tool', price: 0 },
  { id: '123', name: 'Bulma', category: 'Tool', price: 0 },
  { id: '124', name: 'Foundation', category: 'Tool', price: 0 },
  { id: '125', name: 'Semantic UI', category: 'Tool', price: 0 },
  { id: '126', name: 'UIKit', category: 'Tool', price: 0 },
  { id: '127', name: 'Materialize', category: 'Tool', price: 0 },
  { id: '128', name: 'Tachyons', category: 'Tool', price: 0 },
  { id: '129', name: 'Windicss', category: 'Tool', price: 0 },
  { id: '130', name: 'UnoCSS', category: 'Tool', price: 0 },
  { id: '131', name: 'Sass', category: 'Tool', price: 0 },
  { id: '132', name: 'Less', category: 'Tool', price: 0 },
  { id: '133', name: 'Stylus', category: 'Tool', price: 0 },
  { id: '134', name: 'PostCSS', category: 'Tool', price: 0 },
  { id: '135', name: 'Autoprefixer', category: 'Tool', price: 0 },
  { id: '136', name: 'PurgeCSS', category: 'Tool', price: 0 },
  { id: '137', name: 'Critical', category: 'Tool', price: 0 },
  { id: '138', name: 'UnCSS', category: 'Tool', price: 0 },
  { id: '139', name: 'StyleLint', category: 'Tool', price: 0 },
  { id: '140', name: 'CSSNano', category: 'Tool', price: 0 },

  // Testing Tools
  { id: '141', name: 'Vitest', category: 'Testing', price: 0 },
  { id: '142', name: 'Jest', category: 'Testing', price: 0 },
  { id: '143', name: 'Mocha', category: 'Testing', price: 0 },
  { id: '144', name: 'Jasmine', category: 'Testing', price: 0 },
  { id: '145', name: 'Karma', category: 'Testing', price: 0 },
  { id: '146', name: 'Cypress', category: 'Testing', price: 0 },
  { id: '147', name: 'Playwright', category: 'Testing', price: 0 },
  { id: '148', name: 'Puppeteer', category: 'Testing', price: 0 },
  { id: '149', name: 'Selenium', category: 'Testing', price: 0 },
  { id: '150', name: 'WebDriver', category: 'Testing', price: 0 },
  { id: '151', name: 'Testing Library', category: 'Testing', price: 0 },
  { id: '152', name: 'Enzyme', category: 'Testing', price: 0 },
  { id: '153', name: 'Storybook', category: 'Testing', price: 0 },
  { id: '154', name: 'Chromatic', category: 'Testing', price: 0 },
  { id: '155', name: 'Percy', category: 'Testing', price: 0 },
  { id: '156', name: 'Applitools', category: 'Testing', price: 0 },
  { id: '157', name: 'Lighthouse', category: 'Testing', price: 0 },
  { id: '158', name: 'Web Vitals', category: 'Testing', price: 0 },
  { id: '159', name: 'Bundlesize', category: 'Testing', price: 0 },
  { id: '160', name: 'Bundle Analyzer', category: 'Testing', price: 0 },
  { id: '161', name: 'Supertest', category: 'Testing', price: 0 },
  { id: '162', name: 'Nock', category: 'Testing', price: 0 },
  { id: '163', name: 'MSW', category: 'Testing', price: 0 },
  { id: '164', name: 'WireMock', category: 'Testing', price: 0 },
  { id: '165', name: 'Artillery', category: 'Testing', price: 0 },
  { id: '166', name: 'K6', category: 'Testing', price: 0 },
  { id: '167', name: 'JMeter', category: 'Testing', price: 0 },
  { id: '168', name: 'Gatling', category: 'Testing', price: 0 },
  { id: '169', name: 'Locust', category: 'Testing', price: 0 },
  { id: '170', name: 'LoadRunner', category: 'Testing', price: 0 },

  // Databases
  { id: '171', name: 'PostgreSQL', category: 'Database', price: 0 },
  { id: '172', name: 'MySQL', category: 'Database', price: 0 },
  { id: '173', name: 'MariaDB', category: 'Database', price: 0 },
  { id: '174', name: 'SQLite', category: 'Database', price: 0 },
  { id: '175', name: 'MongoDB', category: 'Database', price: 0 },
  { id: '176', name: 'CouchDB', category: 'Database', price: 0 },
  { id: '177', name: 'Redis', category: 'Database', price: 0 },
  { id: '178', name: 'Memcached', category: 'Database', price: 0 },
  { id: '179', name: 'Elasticsearch', category: 'Database', price: 0 },
  { id: '180', name: 'Solr', category: 'Database', price: 0 },
  { id: '181', name: 'Neo4j', category: 'Database', price: 0 },
  { id: '182', name: 'ArangoDB', category: 'Database', price: 0 },
  { id: '183', name: 'InfluxDB', category: 'Database', price: 0 },
  { id: '184', name: 'TimescaleDB', category: 'Database', price: 0 },
  { id: '185', name: 'Cassandra', category: 'Database', price: 0 },
  { id: '186', name: 'ScyllaDB', category: 'Database', price: 0 },
  { id: '187', name: 'DynamoDB', category: 'Database', price: 0 },
  { id: '188', name: 'DocumentDB', category: 'Database', price: 0 },
  { id: '189', name: 'CosmosDB', category: 'Database', price: 0 },
  { id: '190', name: 'FaunaDB', category: 'Database', price: 0 },
  { id: '191', name: 'Supabase', category: 'Database', price: 0 },
  { id: '192', name: 'Firebase', category: 'Database', price: 0 },
  { id: '193', name: 'PlanetScale', category: 'Database', price: 0 },
  { id: '194', name: 'Neon', category: 'Database', price: 0 },
  { id: '195', name: 'Xata', category: 'Database', price: 0 },
  { id: '196', name: 'Prisma', category: 'Database', price: 0 },
  { id: '197', name: 'Drizzle', category: 'Database', price: 0 },
  { id: '198', name: 'TypeORM', category: 'Database', price: 0 },
  { id: '199', name: 'Sequelize', category: 'Database', price: 0 },
  { id: '200', name: 'Mongoose', category: 'Database', price: 0 },

  // Programming Languages
  { id: '201', name: 'JavaScript', category: 'Language', price: 0 },
  { id: '202', name: 'TypeScript', category: 'Language', price: 0 },
  { id: '203', name: 'Python', category: 'Language', price: 0 },
  { id: '204', name: 'Java', category: 'Language', price: 0 },
  { id: '205', name: 'C#', category: 'Language', price: 0 },
  { id: '206', name: 'C++', category: 'Language', price: 0 },
  { id: '207', name: 'C', category: 'Language', price: 0 },
  { id: '208', name: 'Go', category: 'Language', price: 0 },
  { id: '209', name: 'Rust', category: 'Language', price: 0 },
  { id: '210', name: 'Swift', category: 'Language', price: 0 },
  { id: '211', name: 'Kotlin', category: 'Language', price: 0 },
  { id: '212', name: 'Scala', category: 'Language', price: 0 },
  { id: '213', name: 'Ruby', category: 'Language', price: 0 },
  { id: '214', name: 'PHP', category: 'Language', price: 0 },
  { id: '215', name: 'Dart', category: 'Language', price: 0 },
  { id: '216', name: 'Elixir', category: 'Language', price: 0 },
  { id: '217', name: 'Erlang', category: 'Language', price: 0 },
  { id: '218', name: 'Haskell', category: 'Language', price: 0 },
  { id: '219', name: 'OCaml', category: 'Language', price: 0 },
  { id: '220', name: 'F#', category: 'Language', price: 0 },
  { id: '221', name: 'Clojure', category: 'Language', price: 0 },
  { id: '222', name: 'ClojureScript', category: 'Language', price: 0 },
  { id: '223', name: 'Elm', category: 'Language', price: 0 },
  { id: '224', name: 'PureScript', category: 'Language', price: 0 },
  { id: '225', name: 'ReasonML', category: 'Language', price: 0 },
  { id: '226', name: 'Zig', category: 'Language', price: 0 },
  { id: '227', name: 'Nim', category: 'Language', price: 0 },
  { id: '228', name: 'Crystal', category: 'Language', price: 0 },
  { id: '229', name: 'Julia', category: 'Language', price: 0 },
  { id: '230', name: 'R', category: 'Language', price: 0 },
  { id: '231', name: 'MATLAB', category: 'Language', price: 0 },
  { id: '232', name: 'Perl', category: 'Language', price: 0 },
  { id: '233', name: 'Lua', category: 'Language', price: 0 },
  { id: '234', name: 'Assembly', category: 'Language', price: 0 },
  { id: '235', name: 'WASM', category: 'Language', price: 0 },
  { id: '236', name: 'SQL', category: 'Language', price: 0 },
  { id: '237', name: 'GraphQL', category: 'Language', price: 0 },
  { id: '238', name: 'HTML', category: 'Language', price: 0 },
  { id: '239', name: 'CSS', category: 'Language', price: 0 },
  { id: '240', name: 'Sass', category: 'Language', price: 0 },

  // Cloud Services
  { id: '241', name: 'AWS', category: 'Cloud', price: 100 },
  { id: '242', name: 'Google Cloud', category: 'Cloud', price: 95 },
  { id: '243', name: 'Microsoft Azure', category: 'Cloud', price: 90 },
  { id: '244', name: 'Vercel', category: 'Cloud', price: 20 },
  { id: '245', name: 'Netlify', category: 'Cloud', price: 15 },
  { id: '246', name: 'Railway', category: 'Cloud', price: 10 },
  { id: '247', name: 'Render', category: 'Cloud', price: 12 },
  { id: '248', name: 'Fly.io', category: 'Cloud', price: 8 },
  { id: '249', name: 'DigitalOcean', category: 'Cloud', price: 25 },
  { id: '250', name: 'Linode', category: 'Cloud', price: 22 },
  { id: '251', name: 'Vultr', category: 'Cloud', price: 18 },
  { id: '252', name: 'Hetzner', category: 'Cloud', price: 15 },
  { id: '253', name: 'OVH', category: 'Cloud', price: 20 },
  { id: '254', name: 'Cloudflare', category: 'Cloud', price: 5 },
  { id: '255', name: 'Fastly', category: 'Cloud', price: 30 },
  { id: '256', name: 'KeyCDN', category: 'Cloud', price: 8 },
  { id: '257', name: 'BunnyCDN', category: 'Cloud', price: 6 },
  { id: '258', name: 'MaxCDN', category: 'Cloud', price: 12 },
  { id: '259', name: 'CloudFront', category: 'Cloud', price: 15 },
  { id: '260', name: 'Firebase Hosting', category: 'Cloud', price: 10 },

  // DevOps Tools
  { id: '261', name: 'Docker', category: 'DevOps', price: 0 },
  { id: '262', name: 'Kubernetes', category: 'DevOps', price: 0 },
  { id: '263', name: 'Helm', category: 'DevOps', price: 0 },
  { id: '264', name: 'Istio', category: 'DevOps', price: 0 },
  { id: '265', name: 'Envoy', category: 'DevOps', price: 0 },
  { id: '266', name: 'Consul', category: 'DevOps', price: 0 },
  { id: '267', name: 'Vault', category: 'DevOps', price: 0 },
  { id: '268', name: 'Nomad', category: 'DevOps', price: 0 },
  { id: '269', name: 'Terraform', category: 'DevOps', price: 0 },
  { id: '270', name: 'Pulumi', category: 'DevOps', price: 0 },
  { id: '271', name: 'Ansible', category: 'DevOps', price: 0 },
  { id: '272', name: 'Chef', category: 'DevOps', price: 0 },
  { id: '273', name: 'Puppet', category: 'DevOps', price: 0 },
  { id: '274', name: 'SaltStack', category: 'DevOps', price: 0 },
  { id: '275', name: 'Jenkins', category: 'DevOps', price: 0 },
  { id: '276', name: 'GitHub Actions', category: 'DevOps', price: 0 },
  { id: '277', name: 'GitLab CI', category: 'DevOps', price: 0 },
  { id: '278', name: 'CircleCI', category: 'DevOps', price: 20 },
  { id: '279', name: 'Travis CI', category: 'DevOps', price: 15 },
  { id: '280', name: 'Azure Pipelines', category: 'DevOps', price: 0 },
  { id: '281', name: 'TeamCity', category: 'DevOps', price: 50 },
  { id: '282', name: 'Bamboo', category: 'DevOps', price: 45 },
  { id: '283', name: 'BuildKite', category: 'DevOps', price: 25 },
  { id: '284', name: 'Drone', category: 'DevOps', price: 0 },
  { id: '285', name: 'Argo CD', category: 'DevOps', price: 0 },
  { id: '286', name: 'Flux', category: 'DevOps', price: 0 },
  { id: '287', name: 'Spinnaker', category: 'DevOps', price: 0 },
  { id: '288', name: 'Octopus Deploy', category: 'DevOps', price: 40 },
  { id: '289', name: 'AWS CodePipeline', category: 'DevOps', price: 0 },
  { id: '290', name: 'AWS CodeBuild', category: 'DevOps', price: 0 },
  { id: '291', name: 'AWS CodeDeploy', category: 'DevOps', price: 0 },
  { id: '292', name: 'Google Cloud Build', category: 'DevOps', price: 0 },
  { id: '293', name: 'Prometheus', category: 'DevOps', price: 0 },
  { id: '294', name: 'Grafana', category: 'DevOps', price: 0 },
  { id: '295', name: 'Jaeger', category: 'DevOps', price: 0 },
  { id: '296', name: 'Zipkin', category: 'DevOps', price: 0 },
  { id: '297', name: 'OpenTelemetry', category: 'DevOps', price: 0 },
  { id: '298', name: 'ELK Stack', category: 'DevOps', price: 0 },
  { id: '299', name: 'Fluentd', category: 'DevOps', price: 0 },
  { id: '300', name: 'Logstash', category: 'DevOps', price: 0 },

  // Mobile Development
  { id: '301', name: 'React Native', category: 'Framework', price: 0 },
  { id: '302', name: 'Flutter', category: 'Framework', price: 0 },
  { id: '303', name: 'Xamarin', category: 'Framework', price: 0 },
  { id: '304', name: 'Ionic', category: 'Framework', price: 0 },
  { id: '305', name: 'Cordova', category: 'Framework', price: 0 },
  { id: '306', name: 'PhoneGap', category: 'Framework', price: 0 },
  { id: '307', name: 'NativeScript', category: 'Framework', price: 0 },
  { id: '308', name: 'Expo', category: 'Framework', price: 0 },
  { id: '309', name: 'Capacitor', category: 'Framework', price: 0 },
  { id: '310', name: 'Unity', category: 'Framework', price: 0 },
  { id: '311', name: 'Unreal Engine', category: 'Framework', price: 0 },
  { id: '312', name: 'Godot', category: 'Framework', price: 0 },
  { id: '313', name: 'Cocos2d', category: 'Framework', price: 0 },
  { id: '314', name: 'Phaser', category: 'Framework', price: 0 },
  { id: '315', name: 'PixiJS', category: 'Framework', price: 0 },
  { id: '316', name: 'BabylonJS', category: 'Framework', price: 0 },
  { id: '317', name: 'A-Frame', category: 'Framework', price: 0 },
  { id: '318', name: 'AR.js', category: 'Framework', price: 0 },
  { id: '319', name: 'WebXR', category: 'Framework', price: 0 },
  { id: '320', name: 'TensorFlow.js', category: 'Framework', price: 0 },

  // Desktop Development
  { id: '321', name: 'Electron', category: 'Framework', price: 0 },
  { id: '322', name: 'Tauri', category: 'Framework', price: 0 },
  { id: '323', name: 'Neutralino', category: 'Framework', price: 0 },
  { id: '324', name: 'NodeGUI', category: 'Framework', price: 0 },
  { id: '325', name: 'Proton Native', category: 'Framework', price: 0 },
  { id: '326', name: 'Qt', category: 'Framework', price: 0 },
  { id: '327', name: 'GTK', category: 'Framework', price: 0 },
  { id: '328', name: 'WPF', category: 'Framework', price: 0 },
  { id: '329', name: 'WinUI', category: 'Framework', price: 0 },
  { id: '330', name: 'UWP', category: 'Framework', price: 0 },
  { id: '331', name: 'Avalonia', category: 'Framework', price: 0 },
  { id: '332', name: 'MAUI', category: 'Framework', price: 0 },
  { id: '333', name: 'Tkinter', category: 'Framework', price: 0 },
  { id: '334', name: 'PyQt', category: 'Framework', price: 0 },
  { id: '335', name: 'Kivy', category: 'Framework', price: 0 },
  { id: '336', name: 'Dear ImGui', category: 'Framework', price: 0 },
  { id: '337', name: 'FLTK', category: 'Framework', price: 0 },
  { id: '338', name: 'wxWidgets', category: 'Framework', price: 0 },
  { id: '339', name: 'JavaFX', category: 'Framework', price: 0 },
  { id: '340', name: 'Swing', category: 'Framework', price: 0 },

  // AI/ML Tools
  { id: '341', name: 'TensorFlow', category: 'Library', price: 0 },
  { id: '342', name: 'PyTorch', category: 'Library', price: 0 },
  { id: '343', name: 'Keras', category: 'Library', price: 0 },
  { id: '344', name: 'Scikit-learn', category: 'Library', price: 0 },
  { id: '345', name: 'Pandas', category: 'Library', price: 0 },
  { id: '346', name: 'NumPy', category: 'Library', price: 0 },
  { id: '347', name: 'Matplotlib', category: 'Library', price: 0 },
  { id: '348', name: 'Seaborn', category: 'Library', price: 0 },
  { id: '349', name: 'Plotly', category: 'Library', price: 0 },
  { id: '350', name: 'OpenCV', category: 'Library', price: 0 },
  { id: '351', name: 'NLTK', category: 'Library', price: 0 },
  { id: '352', name: 'SpaCy', category: 'Library', price: 0 },
  { id: '353', name: 'Transformers', category: 'Library', price: 0 },
  { id: '354', name: 'LangChain', category: 'Library', price: 0 },
  { id: '355', name: 'LlamaIndex', category: 'Library', price: 0 },
  { id: '356', name: 'Pinecone', category: 'Database', price: 50 },
  { id: '357', name: 'Weaviate', category: 'Database', price: 30 },
  { id: '358', name: 'Chroma', category: 'Database', price: 0 },
  { id: '359', name: 'Milvus', category: 'Database', price: 0 },
  { id: '360', name: 'Qdrant', category: 'Database', price: 0 },

  // Web3/Blockchain
  { id: '361', name: 'Ethereum', category: 'Framework', price: 0 },
  { id: '362', name: 'Solidity', category: 'Language', price: 0 },
  { id: '363', name: 'Web3.js', category: 'Library', price: 0 },
  { id: '364', name: 'Ethers.js', category: 'Library', price: 0 },
  { id: '365', name: 'Hardhat', category: 'Tool', price: 0 },
  { id: '366', name: 'Truffle', category: 'Tool', price: 0 },
  { id: '367', name: 'Ganache', category: 'Tool', price: 0 },
  { id: '368', name: 'MetaMask', category: 'Tool', price: 0 },
  { id: '369', name: 'IPFS', category: 'Tool', price: 0 },
  { id: '370', name: 'The Graph', category: 'Tool', price: 0 },
  { id: '371', name: 'Chainlink', category: 'Tool', price: 0 },
  { id: '372', name: 'OpenZeppelin', category: 'Library', price: 0 },
  { id: '373', name: 'Moralis', category: 'Cloud', price: 25 },
  { id: '374', name: 'Alchemy', category: 'Cloud', price: 30 },
  { id: '375', name: 'Infura', category: 'Cloud', price: 35 },
  { id: '376', name: 'QuickNode', category: 'Cloud', price: 28 },
  { id: '377', name: 'Polygon', category: 'Framework', price: 0 },
  { id: '378', name: 'Avalanche', category: 'Framework', price: 0 },
  { id: '379', name: 'Solana', category: 'Framework', price: 0 },
  { id: '380', name: 'Near', category: 'Framework', price: 0 },

  // CMS & Headless CMS
  { id: '381', name: 'WordPress', category: 'Framework', price: 0 },
  { id: '382', name: 'Drupal', category: 'Framework', price: 0 },
  { id: '383', name: 'Joomla', category: 'Framework', price: 0 },
  { id: '384', name: 'Strapi', category: 'Framework', price: 0 },
  { id: '385', name: 'Contentful', category: 'Cloud', price: 40 },
  { id: '386', name: 'Sanity', category: 'Cloud', price: 35 },
  { id: '387', name: 'Ghost', category: 'Framework', price: 0 },
  { id: '388', name: 'Payload CMS', category: 'Framework', price: 0 },
  { id: '389', name: 'Directus', category: 'Framework', price: 0 },
  { id: '390', name: 'KeystoneJS', category: 'Framework', price: 0 },
  { id: '391', name: 'TinaCMS', category: 'Framework', price: 0 },
  { id: '392', name: 'Forestry', category: 'Cloud', price: 20 },
  { id: '393', name: 'NetlifyCMS', category: 'Framework', price: 0 },
  { id: '394', name: 'DatoCMS', category: 'Cloud', price: 30 },
  { id: '395', name: 'Prismic', category: 'Cloud', price: 25 },
  { id: '396', name: 'Butter CMS', category: 'Cloud', price: 35 },
  { id: '397', name: 'Cockpit', category: 'Framework', price: 0 },
  { id: '398', name: 'Craft CMS', category: 'Framework', price: 299 },
  { id: '399', name: 'ExpressionEngine', category: 'Framework', price: 199 },
  { id: '400', name: 'ProcessWire', category: 'Framework', price: 0 },

  // E-commerce
  { id: '401', name: 'Shopify', category: 'Cloud', price: 29 },
  { id: '402', name: 'WooCommerce', category: 'Framework', price: 0 },
  { id: '403', name: 'Magento', category: 'Framework', price: 0 },
  { id: '404', name: 'PrestaShop', category: 'Framework', price: 0 },
  { id: '405', name: 'OpenCart', category: 'Framework', price: 0 },
  { id: '406', name: 'BigCommerce', category: 'Cloud', price: 39 },
  { id: '407', name: 'Squarespace', category: 'Cloud', price: 18 },
  { id: '408', name: 'Wix', category: 'Cloud', price: 23 },
  { id: '409', name: 'Webflow', category: 'Cloud', price: 23 },
  { id: '410', name: 'Saleor', category: 'Framework', price: 0 },
  { id: '411', name: 'Spree Commerce', category: 'Framework', price: 0 },
  { id: '412', name: 'Sylius', category: 'Framework', price: 0 },
  { id: '413', name: 'nopCommerce', category: 'Framework', price: 0 },
  { id: '414', name: 'osCommerce', category: 'Framework', price: 0 },
  { id: '415', name: 'Zen Cart', category: 'Framework', price: 0 },
  { id: '416', name: 'Next.js Commerce', category: 'Framework', price: 0 },
  { id: '417', name: 'Medusa', category: 'Framework', price: 0 },
  { id: '418', name: 'Vendure', category: 'Framework', price: 0 },
  { id: '419', name: 'Reaction Commerce', category: 'Framework', price: 0 },
  { id: '420', name: 'Gatsby Store', category: 'Framework', price: 0 },

  // API Tools
  { id: '421', name: 'Postman', category: 'Tool', price: 12 },
  { id: '422', name: 'Insomnia', category: 'Tool', price: 0 },
  { id: '423', name: 'Thunder Client', category: 'Tool', price: 0 },
  { id: '424', name: 'REST Client', category: 'Tool', price: 0 },
  { id: '425', name: 'cURL', category: 'Tool', price: 0 },
  { id: '426', name: 'HTTPie', category: 'Tool', price: 0 },
  { id: '427', name: 'Swagger', category: 'Tool', price: 0 },
  { id: '428', name: 'OpenAPI', category: 'Tool', price: 0 },
  { id: '429', name: 'GraphQL Playground', category: 'Tool', price: 0 },
  { id: '430', name: 'Apollo Studio', category: 'Tool', price: 0 },
  { id: '431', name: 'Hasura', category: 'Framework', price: 0 },
  { id: '432', name: 'Supabase', category: 'Framework', price: 0 },
  { id: '433', name: 'AWS AppSync', category: 'Cloud', price: 0 },
  { id: '434', name: 'Fauna GraphQL', category: 'Cloud', price: 25 },
  { id: '435', name: 'Prisma', category: 'Tool', price: 0 },
  { id: '436', name: 'tRPC', category: 'Library', price: 0 },
  { id: '437', name: 'Zod', category: 'Library', price: 0 },
  { id: '438', name: 'Yup', category: 'Library', price: 0 },
  { id: '439', name: 'Joi', category: 'Library', price: 0 },
  { id: '440', name: 'AJV', category: 'Library', price: 0 },

  // Additional Development Tools
  { id: '441', name: 'VS Code', category: 'Tool', price: 0 },
  { id: '442', name: 'WebStorm', category: 'Tool', price: 129 },
  { id: '443', name: 'PhpStorm', category: 'Tool', price: 199 },
  { id: '444', name: 'IntelliJ IDEA', category: 'Tool', price: 499 },
  { id: '445', name: 'PyCharm', category: 'Tool', price: 199 },
  { id: '446', name: 'Rider', category: 'Tool', price: 349 },
  { id: '447', name: 'GoLand', category: 'Tool', price: 199 },
  { id: '448', name: 'CLion', category: 'Tool', price: 199 },
  { id: '449', name: 'RubyMine', category: 'Tool', price: 199 },
  { id: '450', name: 'AppCode', category: 'Tool', price: 199 },
  { id: '451', name: 'DataGrip', category: 'Tool', price: 199 },
  { id: '452', name: 'Atom', category: 'Tool', price: 0 },
  { id: '453', name: 'Sublime Text', category: 'Tool', price: 99 },
  { id: '454', name: 'Vim', category: 'Tool', price: 0 },
  { id: '455', name: 'Neovim', category: 'Tool', price: 0 },
  { id: '456', name: 'Emacs', category: 'Tool', price: 0 },
  { id: '457', name: 'Nano', category: 'Tool', price: 0 },
  { id: '458', name: 'Brackets', category: 'Tool', price: 0 },
  { id: '459', name: 'Code::Blocks', category: 'Tool', price: 0 },
  { id: '460', name: 'Dev-C++', category: 'Tool', price: 0 },

  // Version Control
  { id: '461', name: 'Git', category: 'Tool', price: 0 },
  { id: '462', name: 'GitHub', category: 'Cloud', price: 4 },
  { id: '463', name: 'GitLab', category: 'Cloud', price: 19 },
  { id: '464', name: 'Bitbucket', category: 'Cloud', price: 15 },
  { id: '465', name: 'Azure DevOps', category: 'Cloud', price: 6 },
  { id: '466', name: 'SourceForge', category: 'Cloud', price: 0 },
  { id: '467', name: 'GitKraken', category: 'Tool', price: 59 },
  { id: '468', name: 'Sourcetree', category: 'Tool', price: 0 },
  { id: '469', name: 'Tower', category: 'Tool', price: 69 },
  { id: '470', name: 'Fork', category: 'Tool', price: 49 },
  { id: '471', name: 'Mercurial', category: 'Tool', price: 0 },
  { id: '472', name: 'SVN', category: 'Tool', price: 0 },
  { id: '473', name: 'Perforce', category: 'Tool', price: 89 },
  { id: '474', name: 'Bazaar', category: 'Tool', price: 0 },
  { id: '475', name: 'Darcs', category: 'Tool', price: 0 },
  { id: '476', name: 'Fossil', category: 'Tool', price: 0 },
  { id: '477', name: 'Phabricator', category: 'Tool', price: 0 },
  { id: '478', name: 'Review Board', category: 'Tool', price: 0 },
  { id: '479', name: 'Gerrit', category: 'Tool', price: 0 },
  { id: '480', name: 'Crucible', category: 'Tool', price: 10 },

  // Design Tools
  { id: '481', name: 'Figma', category: 'Tool', price: 15 },
  { id: '482', name: 'Sketch', category: 'Tool', price: 99 },
  { id: '483', name: 'Adobe XD', category: 'Tool', price: 9.99 },
  { id: '484', name: 'InVision', category: 'Tool', price: 25 },
  { id: '485', name: 'Marvel', category: 'Tool', price: 12 },
  { id: '486', name: 'Principle', category: 'Tool', price: 129 },
  { id: '487', name: 'Framer', category: 'Tool', price: 20 },
  { id: '488', name: 'ProtoPie', category: 'Tool', price: 25 },
  { id: '489', name: 'Axure RP', category: 'Tool', price: 25 },
  { id: '490', name: 'Balsamiq', category: 'Tool', price: 89 },
  { id: '491', name: 'Wireframe.cc', category: 'Tool', price: 16 },
  { id: '492', name: 'Mockflow', category: 'Tool', price: 14 },
  { id: '493', name: 'UXPin', category: 'Tool', price: 29 },
  { id: '494', name: 'Proto.io', category: 'Tool', price: 24 },
  { id: '495', name: 'Justinmind', category: 'Tool', price: 19 },
  { id: '496', name: 'Origami Studio', category: 'Tool', price: 0 },
  { id: '497', name: 'Adobe Photoshop', category: 'Tool', price: 20.99 },
  { id: '498', name: 'Adobe Illustrator', category: 'Tool', price: 20.99 },
  { id: '499', name: 'Canva', category: 'Tool', price: 12.99 },
  { id: '500', name: 'GIMP', category: 'Tool', price: 0 },

  // Additional Libraries (501-600)
  { id: '501', name: 'React Hook Form', category: 'Library', price: 0 },
  { id: '502', name: 'Formik', category: 'Library', price: 0 },
  { id: '503', name: 'React Final Form', category: 'Library', price: 0 },
  { id: '504', name: 'React Select', category: 'Library', price: 0 },
  { id: '505', name: 'React Datepicker', category: 'Library', price: 0 },
  { id: '506', name: 'React Table', category: 'Library', price: 0 },
  { id: '507', name: 'React Virtual', category: 'Library', price: 0 },
  { id: '508', name: 'React Window', category: 'Library', price: 0 },
  { id: '509', name: 'React Helmet', category: 'Library', price: 0 },
  { id: '510', name: 'React Intl', category: 'Library', price: 0 },
  { id: '511', name: 'i18next', category: 'Library', price: 0 },
  { id: '512', name: 'React i18next', category: 'Library', price: 0 },
  { id: '513', name: 'React Loadable', category: 'Library', price: 0 },
  { id: '514', name: 'Loadable Components', category: 'Library', price: 0 },
  { id: '515', name: 'React Lazy Load', category: 'Library', price: 0 },
  { id: '516', name: 'React Intersection Observer', category: 'Library', price: 0 },
  { id: '517', name: 'React Use', category: 'Library', price: 0 },
  { id: '518', name: 'React Hooks Lib', category: 'Library', price: 0 },
  { id: '519', name: 'Ahooks', category: 'Library', price: 0 },
  { id: '520', name: 'React Error Boundary', category: 'Library', price: 0 },
  { id: '521', name: 'React Hot Toast', category: 'Library', price: 0 },
  { id: '522', name: 'React Toastify', category: 'Library', price: 0 },
  { id: '523', name: 'React Modal', category: 'Library', price: 0 },
  { id: '524', name: 'React Portal', category: 'Library', price: 0 },
  { id: '525', name: 'React Draggable', category: 'Library', price: 0 },
  { id: '526', name: 'React DnD', category: 'Library', price: 0 },
  { id: '527', name: 'React Sortable HOC', category: 'Library', price: 0 },
  { id: '528', name: 'React Beautiful DnD', category: 'Library', price: 0 },
  { id: '529', name: 'React Dropzone', category: 'Library', price: 0 },
  { id: '530', name: 'React Image Crop', category: 'Library', price: 0 },
  { id: '531', name: 'React Player', category: 'Library', price: 0 },
  { id: '532', name: 'React Audio Player', category: 'Library', price: 0 },
  { id: '533', name: 'React Webcam', category: 'Library', price: 0 },
  { id: '534', name: 'React QR Code', category: 'Library', price: 0 },
  { id: '535', name: 'React Barcode', category: 'Library', price: 0 },
  { id: '536', name: 'React PDF', category: 'Library', price: 0 },
  { id: '537', name: 'React CSV', category: 'Library', price: 0 },
  { id: '538', name: 'React Excel', category: 'Library', price: 0 },
  { id: '539', name: 'React Markdown', category: 'Library', price: 0 },
  { id: '540', name: 'React Syntax Highlighter', category: 'Library', price: 0 },
  { id: '541', name: 'React Code Mirror', category: 'Library', price: 0 },
  { id: '542', name: 'React Ace Editor', category: 'Library', price: 0 },
  { id: '543', name: 'React Monaco Editor', category: 'Library', price: 0 },
  { id: '544', name: 'React Quill', category: 'Library', price: 0 },
  { id: '545', name: 'React Draft Wysiwyg', category: 'Library', price: 0 },
  { id: '546', name: 'Draft.js', category: 'Library', price: 0 },
  { id: '547', name: 'Slate.js', category: 'Library', price: 0 },
  { id: '548', name: 'TipTap', category: 'Library', price: 0 },
  { id: '549', name: 'Lexical', category: 'Library', price: 0 },
  { id: '550', name: 'React Color', category: 'Library', price: 0 },
  { id: '551', name: 'React Slider', category: 'Library', price: 0 },
  { id: '552', name: 'React Rating', category: 'Library', price: 0 },
  { id: '553', name: 'React Star Rating', category: 'Library', price: 0 },
  { id: '554', name: 'React Progress Bar', category: 'Library', price: 0 },
  { id: '555', name: 'React Spinners', category: 'Library', price: 0 },
  { id: '556', name: 'React Loading', category: 'Library', price: 0 },
  { id: '557', name: 'React Skeleton', category: 'Library', price: 0 },
  { id: '558', name: 'React Placeholder', category: 'Library', price: 0 },
  { id: '559', name: 'React Infinite Scroller', category: 'Library', price: 0 },
  { id: '560', name: 'React Waypoint', category: 'Library', price: 0 },
  { id: '561', name: 'React Visibility Sensor', category: 'Library', price: 0 },
  { id: '562', name: 'React Scroll', category: 'Library', price: 0 },
  { id: '563', name: 'React Sticky', category: 'Library', price: 0 },
  { id: '564', name: 'React Affix', category: 'Library', price: 0 },
  { id: '565', name: 'React Collapse', category: 'Library', price: 0 },
  { id: '566', name: 'React Accordion', category: 'Library', price: 0 },
  { id: '567', name: 'React Tabs', category: 'Library', price: 0 },
  { id: '568', name: 'React Carousel', category: 'Library', price: 0 },
  { id: '569', name: 'React Slick', category: 'Library', price: 0 },
  { id: '570', name: 'Swiper React', category: 'Library', price: 0 },
  { id: '571', name: 'React Image Gallery', category: 'Library', price: 0 },
  { id: '572', name: 'React Photo Gallery', category: 'Library', price: 0 },
  { id: '573', name: 'React Lightbox', category: 'Library', price: 0 },
  { id: '574', name: 'React Image Magnify', category: 'Library', price: 0 },
  { id: '575', name: 'React Zoom Pan Pinch', category: 'Library', price: 0 },
  { id: '576', name: 'React Google Maps', category: 'Library', price: 0 },
  { id: '577', name: 'React Mapbox GL', category: 'Library', price: 0 },
  { id: '578', name: 'React Leaflet', category: 'Library', price: 0 },
  { id: '579', name: 'React Calendar', category: 'Library', price: 0 },
  { id: '580', name: 'React Big Calendar', category: 'Library', price: 0 },
  { id: '581', name: 'React Day Picker', category: 'Library', price: 0 },
  { id: '582', name: 'React Time Picker', category: 'Library', price: 0 },
  { id: '583', name: 'React DateTime', category: 'Library', price: 0 },
  { id: '584', name: 'React Countdown', category: 'Library', price: 0 },
  { id: '585', name: 'React Timer', category: 'Library', price: 0 },
  { id: '586', name: 'React Clock', category: 'Library', price: 0 },
  { id: '587', name: 'React Stopwatch', category: 'Library', price: 0 },
  { id: '588', name: 'React Confetti', category: 'Library', price: 0 },
  { id: '589', name: 'React Particles', category: 'Library', price: 0 },
  { id: '590', name: 'React Lottie', category: 'Library', price: 0 },
  { id: '591', name: 'React Transition Group', category: 'Library', price: 0 },
  { id: '592', name: 'React Pose', category: 'Library', price: 0 },
  { id: '593', name: 'React Reveal', category: 'Library', price: 0 },
  { id: '594', name: 'React Flip Move', category: 'Library', price: 0 },
  { id: '595', name: 'React Anime', category: 'Library', price: 0 },
  { id: '596', name: 'React Tween One', category: 'Library', price: 0 },
  { id: '597', name: 'React Auto Sizer', category: 'Library', price: 0 },
  { id: '598', name: 'React Measure', category: 'Library', price: 0 },
  { id: '599', name: 'React Resize Detector', category: 'Library', price: 0 },
  { id: '600', name: 'React Device Detect', category: 'Library', price: 0 },

  // Additional Frameworks (601-700)
  { id: '601', name: 'Astro', category: 'Framework', price: 0 },
  { id: '602', name: 'Fresh', category: 'Framework', price: 0 },
  { id: '603', name: 'Elder.js', category: 'Framework', price: 0 },
  { id: '604', name: 'Eleventy', category: 'Framework', price: 0 },
  { id: '605', name: 'Jekyll', category: 'Framework', price: 0 },
  { id: '606', name: 'Hugo', category: 'Framework', price: 0 },
  { id: '607', name: 'Hexo', category: 'Framework', price: 0 },
  { id: '608', name: 'VuePress', category: 'Framework', price: 0 },
  { id: '609', name: 'Docusaurus', category: 'Framework', price: 0 },
  { id: '610', name: 'GitBook', category: 'Framework', price: 0 },
  { id: '611', name: 'MkDocs', category: 'Framework', price: 0 },
  { id: '612', name: 'Sphinx', category: 'Framework', price: 0 },
  { id: '613', name: 'BookJS', category: 'Framework', price: 0 },
  { id: '614', name: 'Gitiles', category: 'Framework', price: 0 },
  { id: '615', name: 'Docsify', category: 'Framework', price: 0 },
  { id: '616', name: 'VitePress', category: 'Framework', price: 0 },
  { id: '617', name: 'Nextra', category: 'Framework', price: 0 },
  { id: '618', name: 'Starlight', category: 'Framework', price: 0 },
  { id: '619', name: 'Zola', category: 'Framework', price: 0 },
  { id: '620', name: 'Pelican', category: 'Framework', price: 0 },
  { id: '621', name: 'Lektor', category: 'Framework', price: 0 },
  { id: '622', name: 'Nikola', category: 'Framework', price: 0 },
  { id: '623', name: 'Cobalt', category: 'Framework', price: 0 },
  { id: '624', name: 'Sapper', category: 'Framework', price: 0 },
  { id: '625', name: 'Scully', category: 'Framework', price: 0 },
  { id: '626', name: 'Analog', category: 'Framework', price: 0 },
  { id: '627', name: 'Nitro', category: 'Framework', price: 0 },
  { id: '628', name: 'H3', category: 'Framework', price: 0 },
  { id: '629', name: 'Fastly Compute@Edge', category: 'Framework', price: 0 },
  { id: '630', name: 'Cloudflare Workers', category: 'Framework', price: 0 },
  { id: '631', name: 'Deno Deploy', category: 'Framework', price: 0 },
  { id: '632', name: 'Bun.sh', category: 'Framework', price: 0 },
  { id: '633', name: 'WinterJS', category: 'Framework', price: 0 },
  { id: '634', name: 'Hono', category: 'Framework', price: 0 },
  { id: '635', name: 'Worktop', category: 'Framework', price: 0 },
  { id: '636', name: 'Miniflare', category: 'Framework', price: 0 },
  { id: '637', name: 'Wrangler', category: 'Framework', price: 0 },
  { id: '638', name: 'Serverless Framework', category: 'Framework', price: 0 },
  { id: '639', name: 'AWS SAM', category: 'Framework', price: 0 },
  { id: '640', name: 'Serverless Stack', category: 'Framework', price: 0 },
  { id: '641', name: 'Architect', category: 'Framework', price: 0 },
  { id: '642', name: 'Middy', category: 'Framework', price: 0 },
  { id: '643', name: 'Lambda Web Adapter', category: 'Framework', price: 0 },
  { id: '644', name: 'Chalice', category: 'Framework', price: 0 },
  { id: '645', name: 'Zappa', category: 'Framework', price: 0 },
  { id: '646', name: 'Serverless Next.js', category: 'Framework', price: 0 },
  { id: '647', name: 'AWS CDK', category: 'Framework', price: 0 },
  { id: '648', name: 'Azure Functions', category: 'Framework', price: 0 },
  { id: '649', name: 'Google Cloud Functions', category: 'Framework', price: 0 },
  { id: '650', name: 'OpenFaaS', category: 'Framework', price: 0 },
  { id: '651', name: 'Kubeless', category: 'Framework', price: 0 },
  { id: '652', name: 'Fission', category: 'Framework', price: 0 },
  { id: '653', name: 'Nuclio', category: 'Framework', price: 0 },
  { id: '654', name: 'Fn Project', category: 'Framework', price: 0 },
  { id: '655', name: 'IronFunctions', category: 'Framework', price: 0 },
  { id: '656', name: 'Apache OpenWhisk', category: 'Framework', price: 0 },
  { id: '657', name: 'Knative', category: 'Framework', price: 0 },
  { id: '658', name: 'KEDA', category: 'Framework', price: 0 },
  { id: '659', name: 'Dapr', category: 'Framework', price: 0 },
  { id: '660', name: 'Crossplane', category: 'Framework', price: 0 },
  { id: '661', name: 'Backstage', category: 'Framework', price: 0 },
  { id: '662', name: 'Temporal', category: 'Framework', price: 0 },
  { id: '663', name: 'Cadence', category: 'Framework', price: 0 },
  { id: '664', name: 'Apache Airflow', category: 'Framework', price: 0 },
  { id: '665', name: 'Prefect', category: 'Framework', price: 0 },
  { id: '666', name: 'Dagster', category: 'Framework', price: 0 },
  { id: '667', name: 'Luigi', category: 'Framework', price: 0 },
  { id: '668', name: 'Metaflow', category: 'Framework', price: 0 },
  { id: '669', name: 'Kubeflow', category: 'Framework', price: 0 },
  { id: '670', name: 'MLflow', category: 'Framework', price: 0 },
  { id: '671', name: 'Flyte', category: 'Framework', price: 0 },
  { id: '672', name: 'ZenML', category: 'Framework', price: 0 },
  { id: '673', name: 'Kedro', category: 'Framework', price: 0 },
  { id: '674', name: 'Great Expectations', category: 'Framework', price: 0 },
  { id: '675', name: 'dbt', category: 'Framework', price: 0 },
  { id: '676', name: 'Apache Spark', category: 'Framework', price: 0 },
  { id: '677', name: 'Hadoop', category: 'Framework', price: 0 },
  { id: '678', name: 'Apache Kafka', category: 'Framework', price: 0 },
  { id: '679', name: 'Apache Pulsar', category: 'Framework', price: 0 },
  { id: '680', name: 'RabbitMQ', category: 'Framework', price: 0 },
  { id: '681', name: 'NATS', category: 'Framework', price: 0 },
  { id: '682', name: 'Apache ActiveMQ', category: 'Framework', price: 0 },
  { id: '683', name: 'Amazon SQS', category: 'Cloud', price: 0 },
  { id: '684', name: 'Google Pub/Sub', category: 'Cloud', price: 0 },
  { id: '685', name: 'Azure Service Bus', category: 'Cloud', price: 0 },
  { id: '686', name: 'Apache Flink', category: 'Framework', price: 0 },
  { id: '687', name: 'Apache Storm', category: 'Framework', price: 0 },
  { id: '688', name: 'Apache Samza', category: 'Framework', price: 0 },
  { id: '689', name: 'Akka', category: 'Framework', price: 0 },
  { id: '690', name: 'Vert.x', category: 'Framework', price: 0 },
  { id: '691', name: 'Play Framework', category: 'Framework', price: 0 },
  { id: '692', name: 'Ratpack', category: 'Framework', price: 0 },
  { id: '693', name: 'Dropwizard', category: 'Framework', price: 0 },
  { id: '694', name: 'Javalin', category: 'Framework', price: 0 },
  { id: '695', name: 'Spark Java', category: 'Framework', price: 0 },
  { id: '696', name: 'Helidon', category: 'Framework', price: 0 },
  { id: '697', name: 'Open Liberty', category: 'Framework', price: 0 },
  { id: '698', name: 'Payara', category: 'Framework', price: 0 },
  { id: '699', name: 'WildFly', category: 'Framework', price: 0 },
  { id: '700', name: 'TomEE', category: 'Framework', price: 0 },

  // Additional Tools (701-800)
  { id: '701', name: 'Storybook', category: 'Tool', price: 0 },
  { id: '702', name: 'Bit', category: 'Tool', price: 0 },
  { id: '703', name: 'Chromatic', category: 'Tool', price: 20 },
  { id: '704', name: 'Percy', category: 'Tool', price: 29 },
  { id: '705', name: 'Applitools', category: 'Tool', price: 150 },
  { id: '706', name: 'Screener', category: 'Tool', price: 35 },
  { id: '707', name: 'LambdaTest', category: 'Tool', price: 15 },
  { id: '708', name: 'BrowserStack', category: 'Tool', price: 29 },
  { id: '709', name: 'Sauce Labs', category: 'Tool', price: 39 },
  { id: '710', name: 'CrossBrowserTesting', category: 'Tool', price: 29 },
  { id: '711', name: 'TestingBot', category: 'Tool', price: 25 },
  { id: '712', name: 'Perfecto', category: 'Tool', price: 100 },
  { id: '713', name: 'Device Atlas', category: 'Tool', price: 50 },
  { id: '714', name: 'Real Device Cloud', category: 'Tool', price: 40 },
  { id: '715', name: 'BlazeMeter', category: 'Tool', price: 99 },
  { id: '716', name: 'LoadNinja', category: 'Tool', price: 1188 },
  { id: '717', name: 'NeoLoad', category: 'Tool', price: 2000 },
  { id: '718', name: 'WebLOAD', category: 'Tool', price: 1500 },
  { id: '719', name: 'Silk Performer', category: 'Tool', price: 2500 },
  { id: '720', name: 'Rational Performance Tester', category: 'Tool', price: 3000 },
  { id: '721', name: 'New Relic', category: 'Tool', price: 99 },
  { id: '722', name: 'Datadog', category: 'Tool', price: 15 },
  { id: '723', name: 'AppDynamics', category: 'Tool', price: 200 },
  { id: '724', name: 'Dynatrace', category: 'Tool', price: 21 },
  { id: '725', name: 'Splunk', category: 'Tool', price: 150 },
  { id: '726', name: 'LogicMonitor', category: 'Tool', price: 25 },
  { id: '727', name: 'SolarWinds', category: 'Tool', price: 1638 },
  { id: '728', name: 'ManageEngine', category: 'Tool', price: 595 },
  { id: '729', name: 'Nagios', category: 'Tool', price: 1995 },
  { id: '730', name: 'Zabbix', category: 'Tool', price: 0 },
  { id: '731', name: 'Cacti', category: 'Tool', price: 0 },
  { id: '732', name: 'Icinga', category: 'Tool', price: 0 },
  { id: '733', name: 'CheckMK', category: 'Tool', price: 0 },
  { id: '734', name: 'Pandora FMS', category: 'Tool', price: 100 },
  { id: '735', name: 'PRTG', category: 'Tool', price: 1600 },
  { id: '736', name: 'WhatsUp Gold', category: 'Tool', price: 1420 },
  { id: '737', name: 'OpManager', category: 'Tool', price: 715 },
  { id: '738', name: 'Site24x7', category: 'Tool', price: 9 },
  { id: '739', name: 'Pingdom', category: 'Tool', price: 10 },
  { id: '740', name: 'UptimeRobot', category: 'Tool', price: 7 },
  { id: '741', name: 'StatusCake', category: 'Tool', price: 24.99 },
  { id: '742', name: 'Better Uptime', category: 'Tool', price: 18 },
  { id: '743', name: 'Freshping', category: 'Tool', price: 0 },
  { id: '744', name: 'StatusPage', category: 'Tool', price: 29 },
  { id: '745', name: 'Cachet', category: 'Tool', price: 0 },
  { id: '746', name: 'Vigil', category: 'Tool', price: 0 },
  { id: '747', name: 'Statping', category: 'Tool', price: 0 },
  { id: '748', name: 'Upptime', category: 'Tool', price: 0 },
  { id: '749', name: 'Oh Dear', category: 'Tool', price: 10 },
  { id: '750', name: 'Instatus', category: 'Tool', price: 12 },
  { id: '751', name: 'Hyperping', category: 'Tool', price: 5 },
  { id: '752', name: 'NodePing', category: 'Tool', price: 9 },
  { id: '753', name: 'Checkly', category: 'Tool', price: 25 },
  { id: '754', name: 'Ghost Inspector', category: 'Tool', price: 99 },
  { id: '755', name: 'TestCraft', category: 'Tool', price: 99 },
  { id: '756', name: 'Ranorex', category: 'Tool', price: 2290 },
  { id: '757', name: 'TestComplete', category: 'Tool', price: 2439 },
  { id: '758', name: 'Katalon Studio', category: 'Tool', price: 208 },
  { id: '759', name: 'Leapwork', category: 'Tool', price: 2000 },
  { id: '760', name: 'Tricentis Tosca', category: 'Tool', price: 2500 },
  { id: '761', name: 'SmartBear TestLeft', category: 'Tool', price: 1439 },
  { id: '762', name: 'IBM Rational Functional Tester', category: 'Tool', price: 3500 },
  { id: '763', name: 'Micro Focus UFT', category: 'Tool', price: 3000 },
  { id: '764', name: 'Worksoft Certify', category: 'Tool', price: 5000 },
  { id: '765', name: 'Eggplant Digital Automation Intelligence', category: 'Tool', price: 4000 },
  { id: '766', name: 'Mabl', category: 'Tool', price: 45 },
  { id: '767', name: 'TestRigor', category: 'Tool', price: 200 },
  { id: '768', name: 'Testim', category: 'Tool', price: 450 },
  { id: '769', name: 'Functionize', category: 'Tool', price: 500 },
  { id: '770', name: 'Testcraft', category: 'Tool', price: 99 },
  { id: '771', name: 'Rainforest QA', category: 'Tool', price: 500 },
  { id: '772', name: 'Global App Testing', category: 'Tool', price: 40 },
  { id: '773', name: 'Applause', category: 'Tool', price: 100 },
  { id: '774', name: 'Digivante', category: 'Tool', price: 80 },
  { id: '775', name: 'UserTesting', category: 'Tool', price: 49 },
  { id: '776', name: 'Maze', category: 'Tool', price: 99 },
  { id: '777', name: 'Lookback', category: 'Tool', price: 200 },
  { id: '778', name: 'Hotjar', category: 'Tool', price: 39 },
  { id: '779', name: 'FullStory', category: 'Tool', price: 199 },
  { id: '780', name: 'LogRocket', category: 'Tool', price: 99 },
  { id: '781', name: 'Smartlook', category: 'Tool', price: 39 },
  { id: '782', name: 'MouseFlow', category: 'Tool', price: 24 },
  { id: '783', name: 'Crazy Egg', category: 'Tool', price: 24 },
  { id: '784', name: 'Optimizely', category: 'Tool', price: 50000 },
  { id: '785', name: 'VWO', category: 'Tool', price: 199 },
  { id: '786', name: 'Google Optimize', category: 'Tool', price: 0 },
  { id: '787', name: 'Adobe Target', category: 'Tool', price: 10000 },
  { id: '788', name: 'Unbounce', category: 'Tool', price: 90 },
  { id: '789', name: 'Instapage', category: 'Tool', price: 199 },
  { id: '790', name: 'Leadpages', category: 'Tool', price: 25 },
  { id: '791', name: 'ClickFunnels', category: 'Tool', price: 97 },
  { id: '792', name: 'ConvertKit', category: 'Tool', price: 29 },
  { id: '793', name: 'Mailchimp', category: 'Tool', price: 10 },
  { id: '794', name: 'Constant Contact', category: 'Tool', price: 20 },
  { id: '795', name: 'AWeber', category: 'Tool', price: 16.15 },
  { id: '796', name: 'GetResponse', category: 'Tool', price: 15 },
  { id: '797', name: 'Campaign Monitor', category: 'Tool', price: 9 },
  { id: '798', name: 'SendinBlue', category: 'Tool', price: 25 },
  { id: '799', name: 'ActiveCampaign', category: 'Tool', price: 15 },
  { id: '800', name: 'Drip', category: 'Tool', price: 19 },

  // Additional Databases (801-900)
  { id: '801', name: 'CockroachDB', category: 'Database', price: 0 },
  { id: '802', name: 'YugabyteDB', category: 'Database', price: 0 },
  { id: '803', name: 'VoltDB', category: 'Database', price: 0 },
  { id: '804', name: 'MemSQL', category: 'Database', price: 0 },
  { id: '805', name: 'TiDB', category: 'Database', price: 0 },
  { id: '806', name: 'CrateDB', category: 'Database', price: 0 },
  { id: '807', name: 'QuestDB', category: 'Database', price: 0 },
  { id: '808', name: 'ClickHouse', category: 'Database', price: 0 },
  { id: '809', name: 'Apache Druid', category: 'Database', price: 0 },
  { id: '810', name: 'Apache Pinot', category: 'Database', price: 0 },
  { id: '811', name: 'StarRocks', category: 'Database', price: 0 },
  { id: '812', name: 'Apache Doris', category: 'Database', price: 0 },
  { id: '813', name: 'Greenplum', category: 'Database', price: 0 },
  { id: '814', name: 'Vertica', category: 'Database', price: 0 },
  { id: '815', name: 'Snowflake', category: 'Database', price: 40 },
  { id: '816', name: 'BigQuery', category: 'Database', price: 0.01 },
  { id: '817', name: 'Redshift', category: 'Database', price: 0.25 },
  { id: '818', name: 'Azure Synapse', category: 'Database', price: 1.20 },
  { id: '819', name: 'Databricks', category: 'Database', price: 0.20 },
  { id: '820', name: 'Apache Kylin', category: 'Database', price: 0 },
  { id: '821', name: 'Apache Calcite', category: 'Database', price: 0 },
  { id: '822', name: 'Presto', category: 'Database', price: 0 },
  { id: '823', name: 'Trino', category: 'Database', price: 0 },
  { id: '824', name: 'Apache Drill', category: 'Database', price: 0 },
  { id: '825', name: 'Dremio', category: 'Database', price: 0 },
  { id: '826', name: 'Starburst', category: 'Database', price: 0 },
  { id: '827', name: 'SingleStore', category: 'Database', price: 0.50 },
  { id: '828', name: 'PingCAP TiDB', category: 'Database', price: 0 },
  { id: '829', name: 'Amazon Aurora', category: 'Database', price: 0.10 },
  { id: '830', name: 'Google Cloud SQL', category: 'Database', price: 0.0150 },
  { id: '831', name: 'Azure Database', category: 'Database', price: 0.018 },
  { id: '832', name: 'RDS', category: 'Database', price: 0.017 },
  { id: '833', name: 'Google Firestore', category: 'Database', price: 0.18 },
  { id: '834', name: 'AWS DocumentDB', category: 'Database', price: 0.20 },
  { id: '835', name: 'Azure Cosmos DB', category: 'Database', price: 0.008 },
  { id: '836', name: 'Amazon Neptune', category: 'Database', price: 0.10 },
  { id: '837', name: 'Azure Database for PostgreSQL', category: 'Database', price: 0.018 },
  { id: '838', name: 'Google Cloud Spanner', category: 'Database', price: 0.90 },
  { id: '839', name: 'Amazon Timestream', category: 'Database', price: 0.50 },
  { id: '840', name: 'Google Cloud Bigtable', category: 'Database', price: 0.17 },
  { id: '841', name: 'Amazon QLDB', category: 'Database', price: 1.25 },
  { id: '842', name: 'Azure SQL Edge', category: 'Database', price: 60 },
  { id: '843', name: 'EdgeDB', category: 'Database', price: 0 },
  { id: '844', name: 'SurrealDB', category: 'Database', price: 0 },
  { id: '845', name: 'PlanetScale', category: 'Database', price: 29 },
  { id: '846', name: 'FaunaDB', category: 'Database', price: 25 },
  { id: '847', name: 'Upstash', category: 'Database', price: 0.20 },
  { id: '848', name: 'Railway PostgreSQL', category: 'Database', price: 5 },
  { id: '849', name: 'Render PostgreSQL', category: 'Database', price: 7 },
  { id: '850', name: 'Heroku Postgres', category: 'Database', price: 9 },
  { id: '851', name: 'DigitalOcean Managed Database', category: 'Database', price: 15 },
  { id: '852', name: 'Linode Managed Database', category: 'Database', price: 12 },
  { id: '853', name: 'Vultr Managed Database', category: 'Database', price: 12 },
  { id: '854', name: 'Scaleway Database', category: 'Database', price: 10 },
  { id: '855', name: 'OVHcloud Database', category: 'Database', price: 8 },
  { id: '856', name: 'Aiven', category: 'Database', price: 25 },
  { id: '857', name: 'ElephantSQL', category: 'Database', price: 20 },
  { id: '858', name: 'JawsDB', category: 'Database', price: 10 },
  { id: '859', name: 'ClearDB', category: 'Database', price: 9.99 },
  { id: '860', name: 'mLab', category: 'Database', price: 15 },
  { id: '861', name: 'MongoDB Atlas', category: 'Database', price: 57 },
  { id: '862', name: 'Redis Labs', category: 'Database', price: 7 },
  { id: '863', name: 'Amazon ElastiCache', category: 'Database', price: 0.017 },
  { id: '864', name: 'Google Memorystore', category: 'Database', price: 0.049 },
  { id: '865', name: 'Azure Cache for Redis', category: 'Database', price: 0.008 },
  { id: '866', name: 'KeyDB', category: 'Database', price: 0 },
  { id: '867', name: 'Dragonfly', category: 'Database', price: 0 },
  { id: '868', name: 'Apache Ignite', category: 'Database', price: 0 },
  { id: '869', name: 'Hazelcast', category: 'Database', price: 0 },
  { id: '870', name: 'GridGain', category: 'Database', price: 0 },
  { id: '871', name: 'Apache Geode', category: 'Database', price: 0 },
  { id: '872', name: 'Oracle Coherence', category: 'Database', price: 0 },
  { id: '873', name: 'IBM DB2', category: 'Database', price: 0 },
  { id: '874', name: 'Oracle Database', category: 'Database', price: 0 },
  { id: '875', name: 'SQL Server', category: 'Database', price: 0 },
  { id: '876', name: 'Sybase', category: 'Database', price: 0 },
  { id: '877', name: 'Informix', category: 'Database', price: 0 },
  { id: '878', name: 'Ingres', category: 'Database', price: 0 },
  { id: '879', name: 'Firebird', category: 'Database', price: 0 },
  { id: '880', name: 'HSQLDB', category: 'Database', price: 0 },
  { id: '881', name: 'H2', category: 'Database', price: 0 },
  { id: '882', name: 'Apache Derby', category: 'Database', price: 0 },
  { id: '883', name: 'DuckDB', category: 'Database', price: 0 },
  { id: '884', name: 'LanceDB', category: 'Database', price: 0 },
  { id: '885', name: 'Chroma Vector DB', category: 'Database', price: 0 },
  { id: '886', name: 'Weaviate Vector DB', category: 'Database', price: 0 },
  { id: '887', name: 'Pinecone Vector DB', category: 'Database', price: 70 },
  { id: '888', name: 'Qdrant Vector DB', category: 'Database', price: 0 },
  { id: '889', name: 'Milvus Vector DB', category: 'Database', price: 0 },
  { id: '890', name: 'Vespa', category: 'Database', price: 0 },
  { id: '891', name: 'Jina', category: 'Database', price: 0 },
  { id: '892', name: 'Annoy', category: 'Database', price: 0 },
  { id: '893', name: 'Faiss', category: 'Database', price: 0 },
  { id: '894', name: 'ScaNN', category: 'Database', price: 0 },
  { id: '895', name: 'NGT', category: 'Database', price: 0 },
  { id: '896', name: 'Hierarchical Navigable Small World', category: 'Database', price: 0 },
  { id: '897', name: 'OpenSearch', category: 'Database', price: 0 },
  { id: '898', name: 'Amazon OpenSearch', category: 'Database', price: 0.14 },
  { id: '899', name: 'Elastic Cloud', category: 'Database', price: 95 },
  { id: '900', name: 'Solr Cloud', category: 'Database', price: 0 },

  // Additional Languages (901-1000)
  { id: '901', name: 'V', category: 'Language', price: 0 },
  { id: '902', name: 'Odin', category: 'Language', price: 0 },
  { id: '903', name: 'Carbon', category: 'Language', price: 0 },
  { id: '904', name: 'Mojo', category: 'Language', price: 0 },
  { id: '905', name: 'Red', category: 'Language', price: 0 },
  { id: '906', name: 'Pony', category: 'Language', price: 0 },
  { id: '907', name: 'Chapel', category: 'Language', price: 0 },
  { id: '908', name: 'X10', category: 'Language', price: 0 },
  { id: '909', name: 'Fortress', category: 'Language', price: 0 },
  { id: '910', name: 'Racket', category: 'Language', price: 0 },
  { id: '911', name: 'Scheme', category: 'Language', price: 0 },
  { id: '912', name: 'Common Lisp', category: 'Language', price: 0 },
  { id: '913', name: 'Prolog', category: 'Language', price: 0 },
  { id: '914', name: 'Mercury', category: 'Language', price: 0 },
  { id: '915', name: 'Datalog', category: 'Language', price: 0 },
  { id: '916', name: 'Oz', category: 'Language', price: 0 },
  { id: '917', name: 'Alice', category: 'Language', price: 0 },
  { id: '918', name: 'Mozart', category: 'Language', price: 0 },
  { id: '919', name: 'Eiffel', category: 'Language', price: 0 },
  { id: '920', name: 'Smalltalk', category: 'Language', price: 0 },
  { id: '921', name: 'Squeak', category: 'Language', price: 0 },
  { id: '922', name: 'Pharo', category: 'Language', price: 0 },
  { id: '923', name: 'Self', category: 'Language', price: 0 },
  { id: '924', name: 'Io', category: 'Language', price: 0 },
  { id: '925', name: 'Factor', category: 'Language', price: 0 },
  { id: '926', name: 'Joy', category: 'Language', price: 0 },
  { id: '927', name: 'Forth', category: 'Language', price: 0 },
  { id: '928', name: 'PostScript', category: 'Language', price: 0 },
  { id: '929', name: 'Logo', category: 'Language', price: 0 },
  { id: '930', name: 'APL', category: 'Language', price: 0 },
  { id: '931', name: 'J', category: 'Language', price: 0 },
  { id: '932', name: 'K', category: 'Language', price: 0 },
  { id: '933', name: 'Q', category: 'Language', price: 0 },
  { id: '934', name: 'Kdb+', category: 'Language', price: 0 },
  { id: '935', name: 'S', category: 'Language', price: 0 },
  { id: '936', name: 'S-Plus', category: 'Language', price: 0 },
  { id: '937', name: 'SAS', category: 'Language', price: 0 },
  { id: '938', name: 'SPSS', category: 'Language', price: 0 },
  { id: '939', name: 'Stata', category: 'Language', price: 0 },
  { id: '940', name: 'Minitab', category: 'Language', price: 0 },
  { id: '941', name: 'Octave', category: 'Language', price: 0 },
  { id: '942', name: 'Scilab', category: 'Language', price: 0 },
  { id: '943', name: 'Maxima', category: 'Language', price: 0 },
  { id: '944', name: 'Maple', category: 'Language', price: 0 },
  { id: '945', name: 'Mathematica', category: 'Language', price: 0 },
  { id: '946', name: 'Wolfram Language', category: 'Language', price: 0 },
  { id: '947', name: 'Sage', category: 'Language', price: 0 },
  { id: '948', name: 'SymPy', category: 'Language', price: 0 },
  { id: '949', name: 'NumPy', category: 'Language', price: 0 },
  { id: '950', name: 'SciPy', category: 'Language', price: 0 },
  { id: '951', name: 'Pandas', category: 'Language', price: 0 },
  { id: '952', name: 'Jupyter', category: 'Language', price: 0 },
  { id: '953', name: 'IPython', category: 'Language', price: 0 },
  { id: '954', name: 'Anaconda', category: 'Language', price: 0 },
  { id: '955', name: 'Miniconda', category: 'Language', price: 0 },
  { id: '956', name: 'Conda', category: 'Language', price: 0 },
  { id: '957', name: 'Pip', category: 'Language', price: 0 },
  { id: '958', name: 'Poetry', category: 'Language', price: 0 },
  { id: '959', name: 'Pipenv', category: 'Language', price: 0 },
  { id: '960', name: 'Virtualenv', category: 'Language', price: 0 },
  { id: '961', name: 'Pyenv', category: 'Language', price: 0 },
  { id: '962', name: 'Conda-forge', category: 'Language', price: 0 },
  { id: '963', name: 'PyPI', category: 'Language', price: 0 },
  { id: '964', name: 'Wheel', category: 'Language', price: 0 },
  { id: '965', name: 'Setuptools', category: 'Language', price: 0 },
  { id: '966', name: 'Distutils', category: 'Language', price: 0 },
  { id: '967', name: 'Twine', category: 'Language', price: 0 },
  { id: '968', name: 'Flit', category: 'Language', price: 0 },
  { id: '969', name: 'PDM', category: 'Language', price: 0 },
  { id: '970', name: 'Hatch', category: 'Language', price: 0 },
  { id: '971', name: 'Rye', category: 'Language', price: 0 },
  { id: '972', name: 'UV', category: 'Language', price: 0 },
  { id: '973', name: 'Maturin', category: 'Language', price: 0 },
  { id: '974', name: 'PyO3', category: 'Language', price: 0 },
  { id: '975', name: 'Pydantic', category: 'Language', price: 0 },
  { id: '976', name: 'SQLAlchemy', category: 'Language', price: 0 },
  { id: '977', name: 'Django ORM', category: 'Language', price: 0 },
  { id: '978', name: 'Peewee', category: 'Language', price: 0 },
  { id: '979', name: 'Tortoise ORM', category: 'Language', price: 0 },
  { id: '980', name: 'Orator', category: 'Language', price: 0 },
  { id: '981', name: 'Records', category: 'Language', price: 0 },
  { id: '982', name: 'Dataset', category: 'Language', price: 0 },
  { id: '983', name: 'PyMongo', category: 'Language', price: 0 },
  { id: '984', name: 'Motor', category: 'Language', price: 0 },
  { id: '985', name: 'MongoEngine', category: 'Language', price: 0 },
  { id: '986', name: 'Beanie', category: 'Language', price: 0 },
  { id: '987', name: 'ODMantic', category: 'Language', price: 0 },
  { id: '988', name: 'Redis-py', category: 'Language', price: 0 },
  { id: '989', name: 'Aioredis', category: 'Language', price: 0 },
  { id: '990', name: 'Celery', category: 'Language', price: 0 },
  { id: '991', name: 'RQ', category: 'Language', price: 0 },
  { id: '992', name: 'Dramatiq', category: 'Language', price: 0 },
  { id: '993', name: 'Arq', category: 'Language', price: 0 },
  { id: '994', name: 'Huey', category: 'Language', price: 0 },
  { id: '995', name: 'Dask', category: 'Language', price: 0 },
  { id: '996', name: 'Ray', category: 'Language', price: 0 },
  { id: '997', name: 'Multiprocessing', category: 'Language', price: 0 },
  { id: '998', name: 'Asyncio', category: 'Language', price: 0 },
  { id: '999', name: 'Trio', category: 'Language', price: 0 },
  { id: '1000', name: 'AnyIO', category: 'Language', price: 0 },

  // Additional items to reach over 1000
  { id: '1001', name: 'Uvicorn', category: 'Tool', price: 0 },
  { id: '1002', name: 'Gunicorn', category: 'Tool', price: 0 },
  { id: '1003', name: 'uWSGI', category: 'Tool', price: 0 },
  { id: '1004', name: 'Hypercorn', category: 'Tool', price: 0 },
  { id: '1005', name: 'Daphne', category: 'Tool', price: 0 },
  { id: '1006', name: 'Waitress', category: 'Tool', price: 0 },
  { id: '1007', name: 'Tornado', category: 'Framework', price: 0 },
  { id: '1008', name: 'Aiohttp', category: 'Framework', price: 0 },
  { id: '1009', name: 'Sanic', category: 'Framework', price: 0 },
  { id: '1010', name: 'Quart', category: 'Framework', price: 0 },
  { id: '1011', name: 'Starlette', category: 'Framework', price: 0 },
  { id: '1012', name: 'Responder', category: 'Framework', price: 0 },
  { id: '1013', name: 'Falcon', category: 'Framework', price: 0 },
  { id: '1014', name: 'Bottle', category: 'Framework', price: 0 },
  { id: '1015', name: 'CherryPy', category: 'Framework', price: 0 },
  { id: '1016', name: 'Web2py', category: 'Framework', price: 0 },
  { id: '1017', name: 'TurboGears', category: 'Framework', price: 0 },
  { id: '1018', name: 'Pyramid', category: 'Framework', price: 0 },
  { id: '1019', name: 'Zope', category: 'Framework', price: 0 },
  { id: '1020', name: 'Plone', category: 'Framework', price: 0 }
];